USE [SIMPDB]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_CLIENTE]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_CLIENTE](
	[PK_TBL_SIMP_CLIENTE] [bigint] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[PRIMER_APELLIDO] [varchar](50) NULL,
	[SEGUNDO_APELLIDO] [varchar](50) NULL,
	[CORREO_ELECTRONICO] [varchar](50) NULL,
	[TELEFONO] [varchar](15) NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_ESTADO]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_ESTADO](
	[PK_TBL_SIMP_ESTADO] [bigint] NOT NULL,
	[DESCRIPCION] [varchar](25) NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_ESTADO] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_ESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_PY_ACTIVIDAD]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_PY_ACTIVIDAD](
	[PK_TBL_SIMP_PY_ACTIVIDAD] [bigint] NOT NULL,
	[FK_TBL_SIMP_PY_FASE] [bigint] NOT NULL,
	[FK_TBL_SIMP_USUARIO] [bigint] NOT NULL,
	[FK_TBL_SIMP_ESTADO] [bigint] NOT NULL,
	[DESCRIPCION] [varchar](250) NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_ESTIMADA] [datetime] NULL,
	[FECHA_FINALIZACION] [datetime] NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_ACTIVIDAD] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_PY_ACTIVIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_PY_FASE]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_PY_FASE](
	[PK_TBL_SIMP_PY_FASE] [bigint] NOT NULL,
	[FK_TBL_SIMP_PY_PROYECTO] [bigint] NOT NULL,
	[FK_TBL_SIMP_ESTADO] [bigint] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_FASE] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_PY_FASE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_PY_PROYECTO]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_PY_PROYECTO](
	[PK_TBL_SIMP_PY_PROYECTO] [bigint] NOT NULL,
	[FK_TBL_SIMP_CLIENTE] [bigint] NOT NULL,
	[FK_TBL_SIMP_ESTADO] [bigint] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[DESCRIPCION] [varchar](250) NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_ESTIMADA] [datetime] NULL,
	[FECHA_FINALIZACION] [datetime] NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_PROYECTO] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_PY_PROYECTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_ROL]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_ROL](
	[PK_TBL_SIMP_ROL] [bigint] NOT NULL,
	[DESCRIPCION] [varchar](25) NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_ROL] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_SEG_MENU]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_SEG_MENU](
	[PK_TBL_SIMP_SEG_MENU] [bigint] IDENTITY(1,1) NOT NULL,
	[CODIGO_PADRE] [varchar](100) NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[ICONO] [varchar](100) NULL,
	[URL] [varchar](100) NULL,
	[ESTADO] [char](1) NULL,
	[CREAR] [bit] NULL,
	[EDITAR] [bit] NULL,
	[VER] [bit] NULL,
	[ENVIAR] [bit] NULL,
	[FECHA_CREACION] [datetime] NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
 CONSTRAINT [PK_TBL_SIMP_SEG_MENU] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_SEG_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_SEG_PERFIL]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_SEG_PERFIL](
	[PK_TBL_SIMP_SEG_PERFIL] [bigint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[ESTADO] [varchar](1) NOT NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_FLOW_PERFIL] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_SEG_PERFIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_SEG_PERMISOS]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_SEG_PERMISOS](
	[PK_TBL_SIMP_SEG_PERMISOS] [bigint] IDENTITY(1,1) NOT NULL,
	[FK_TBL_SIMP_SEG_PERFIL] [bigint] NOT NULL,
	[FK_TBL_SIMP_SEG_MENU] [bigint] NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[ESTADO] [char](1) NULL,
	[CREAR] [bit] NULL,
	[EDITAR] [bit] NULL,
	[VER] [bit] NULL,
	[ENVIAR] [bit] NULL,
	[FECHA_CREACION] [datetime] NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
 CONSTRAINT [PK_TBL_SIMP_SEG_PERMISOS] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_SEG_PERMISOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_SEG_USUARIO]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_SEG_USUARIO](
	[PK_TBL_SIMP_SEG_USUARIO] [bigint] NOT NULL,
	[FK_TBL_SIMP_ROL] [bigint] NOT NULL,
	[FK_TBL_SIMP_ESTADO] [bigint] NULL,
	[NOMBRE] [varchar](50) NULL,
	[PRIMER_APELLIDO] [varchar](50) NULL,
	[SEGUNDO_APELLIDO] [varchar](50) NULL,
	[USUARIO] [varchar](50) NULL,
	[CONTRASENA] [varbinary](max) NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_SIMP_SEG_USUARIO] PRIMARY KEY CLUSTERED 
(
	[PK_TBL_SIMP_SEG_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_SIMP_USUARIOXPROYECTO]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_SIMP_USUARIOXPROYECTO](
	[PK_FK_TBL_SIMP_USUARIO] [bigint] NOT NULL,
	[PK_FK_TBL_SIMP_PROYECTO] [bigint] NOT NULL,
	[FECHA] [datetime] NULL,
	[USUARIO_CREACION] [varchar](20) NULL,
	[USUARIO_MODIFICACION] [varchar](20) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_TBL_USUARIOXPROYECTO] PRIMARY KEY CLUSTERED 
(
	[PK_FK_TBL_SIMP_USUARIO] ASC,
	[PK_FK_TBL_SIMP_PROYECTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SITSA].[TBL_TRA_EXCEPCION]    Script Date: 19/9/2022 12:55:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TBL_TRA_EXCEPCION](
	[BIN_PK_TBL_TRA_EXCEPCION] [bigint] IDENTITY(1,1) NOT NULL,
	[SIN_FK_UTL_PAR_PAIS] [smallint] NULL,
	[STR_USUARIO_CREACION] [varchar](50) NULL,
	[FEC_CREACION] [datetime] NULL,
	[STR_USUARIO_MODIFICACION] [varchar](50) NULL,
	[FEC_MODIFICACION] [datetime] NULL,
	[INT_ID_SPID] [int] NULL,
	[FEC_SISTEMA] [datetime] NULL,
	[INT_PRIORIDAD] [int] NULL,
	[INT_SEVERIDAD] [int] NULL,
	[INT_ERROR_ESTADO] [int] NULL,
	[STR_SERVIDOR] [varchar](300) NULL,
	[STR_ESTACION] [varchar](300) NULL,
	[STR_BASE_DATOS] [varchar](300) NULL,
	[STR_APLICATIVO] [varchar](300) NULL,
	[STR_CLASE] [varchar](300) NULL,
	[STR_EVENTO] [varchar](300) NULL,
	[STR_PROCESO] [varchar](300) NULL,
	[STR_PARAMETROS] [varchar](max) NULL,
	[INT_ID_ORIGEN] [int] NULL,
	[STR_DESCRIPCION_ORIGEN] [varchar](300) NULL,
	[INT_ID_TIPO] [int] NULL,
	[STR_DESCRIPCION_TIPO] [varchar](300) NULL,
	[STR_DETALLE] [varchar](500) NULL,
	[STR_MENSAJE] [varchar](max) NULL,
	[STR_MENSAJE_SISTEMA] [varchar](max) NULL,
	[STR_OBSERVACION] [varchar](max) NULL,
	[STR_OTROS_DATOS] [varchar](max) NULL,
	[STR_SENTENCIA] [varchar](max) NULL,
	[INT_NUMERO_USUARIO] [int] NULL,
	[INT_NUMERO_SISTEMA] [int] NULL,
	[INT_NIVEL_ANIDAMIENTO] [int] NULL,
	[INT_NUMERO_LINEA] [int] NULL,
	[STR_IDENTIFICADOR_EXTERNO] [varchar](50) NULL,
	[UNQ_IDENTIFICADOR_UNICO] [uniqueidentifier] NULL,
 CONSTRAINT [PK_TBL_TRA_EXCEPCION] PRIMARY KEY CLUSTERED 
(
	[BIN_PK_TBL_TRA_EXCEPCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [TBL_SIMP_SEG_MENU] ADD  CONSTRAINT [DF__TBL_SIMP_S__ENVIA__09B8B6B2]  DEFAULT ((0)) FOR [ENVIAR]
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS] ADD  CONSTRAINT [DF__TBL_SIMP_S__CREAR__71E12D21]  DEFAULT ((0)) FOR [CREAR]
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS] ADD  CONSTRAINT [DF__TBL_SIMP_S__EDITA__72D5515A]  DEFAULT ((0)) FOR [EDITAR]
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS] ADD  CONSTRAINT [DF__TBL_SIMP_SEG__VER__73C97593]  DEFAULT ((0)) FOR [VER]
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS] ADD  CONSTRAINT [DF__TBL_SIMP_S__ENVIA__0AACDAEB]  DEFAULT ((0)) FOR [ENVIAR]
GO
ALTER TABLE [TBL_SIMP_PY_ACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ESTADOA] FOREIGN KEY([FK_TBL_SIMP_ESTADO])
REFERENCES [TBL_SIMP_ESTADO] ([PK_TBL_SIMP_ESTADO])
GO
ALTER TABLE [TBL_SIMP_PY_ACTIVIDAD] CHECK CONSTRAINT [FK_TBL_ESTADOA]
GO
ALTER TABLE [TBL_SIMP_PY_ACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_TBL_FASE] FOREIGN KEY([FK_TBL_SIMP_PY_FASE])
REFERENCES [TBL_SIMP_PY_FASE] ([PK_TBL_SIMP_PY_FASE])
GO
ALTER TABLE [TBL_SIMP_PY_ACTIVIDAD] CHECK CONSTRAINT [FK_TBL_FASE]
GO
ALTER TABLE [TBL_SIMP_PY_ACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_TBL_USUARIO] FOREIGN KEY([FK_TBL_SIMP_USUARIO])
REFERENCES [TBL_SIMP_SEG_USUARIO] ([PK_TBL_SIMP_SEG_USUARIO])
GO
ALTER TABLE [TBL_SIMP_PY_ACTIVIDAD] CHECK CONSTRAINT [FK_TBL_USUARIO]
GO
ALTER TABLE [TBL_SIMP_PY_FASE]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ESTADO] FOREIGN KEY([FK_TBL_SIMP_ESTADO])
REFERENCES [TBL_SIMP_ESTADO] ([PK_TBL_SIMP_ESTADO])
GO
ALTER TABLE [TBL_SIMP_PY_FASE] CHECK CONSTRAINT [FK_TBL_ESTADO]
GO
ALTER TABLE [TBL_SIMP_PY_FASE]  WITH CHECK ADD  CONSTRAINT [FK_TBL_PROYECTO] FOREIGN KEY([FK_TBL_SIMP_PY_PROYECTO])
REFERENCES [TBL_SIMP_PY_PROYECTO] ([PK_TBL_SIMP_PY_PROYECTO])
GO
ALTER TABLE [TBL_SIMP_PY_FASE] CHECK CONSTRAINT [FK_TBL_PROYECTO]
GO
ALTER TABLE [TBL_SIMP_PY_PROYECTO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_CLIENTE] FOREIGN KEY([FK_TBL_SIMP_CLIENTE])
REFERENCES [TBL_SIMP_CLIENTE] ([PK_TBL_SIMP_CLIENTE])
GO
ALTER TABLE [TBL_SIMP_PY_PROYECTO] CHECK CONSTRAINT [FK_TBL_CLIENTE]
GO
ALTER TABLE [TBL_SIMP_PY_PROYECTO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ESTADOP] FOREIGN KEY([FK_TBL_SIMP_ESTADO])
REFERENCES [TBL_SIMP_ESTADO] ([PK_TBL_SIMP_ESTADO])
GO
ALTER TABLE [TBL_SIMP_PY_PROYECTO] CHECK CONSTRAINT [FK_TBL_ESTADOP]
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SIMP_SEG_MENU] FOREIGN KEY([FK_TBL_SIMP_SEG_MENU])
REFERENCES [TBL_SIMP_SEG_MENU] ([PK_TBL_SIMP_SEG_MENU])
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS] CHECK CONSTRAINT [FK_TBL_SIMP_SEG_MENU]
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SIMP_SEG_PERFIL_PERMISO] FOREIGN KEY([FK_TBL_SIMP_SEG_PERFIL])
REFERENCES [TBL_SIMP_SEG_PERFIL] ([PK_TBL_SIMP_SEG_PERFIL])
GO
ALTER TABLE [TBL_SIMP_SEG_PERMISOS] CHECK CONSTRAINT [FK_TBL_SIMP_SEG_PERFIL_PERMISO]
GO
ALTER TABLE [TBL_SIMP_SEG_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ESTADOU] FOREIGN KEY([FK_TBL_SIMP_ESTADO])
REFERENCES [TBL_SIMP_ESTADO] ([PK_TBL_SIMP_ESTADO])
GO
ALTER TABLE [TBL_SIMP_SEG_USUARIO] CHECK CONSTRAINT [FK_TBL_ESTADOU]
GO
ALTER TABLE [TBL_SIMP_SEG_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ROL] FOREIGN KEY([FK_TBL_SIMP_ROL])
REFERENCES [TBL_SIMP_ROL] ([PK_TBL_SIMP_ROL])
GO
ALTER TABLE [TBL_SIMP_SEG_USUARIO] CHECK CONSTRAINT [FK_TBL_ROL]
GO
ALTER TABLE [TBL_SIMP_USUARIOXPROYECTO]  WITH CHECK ADD  CONSTRAINT [PK_FK_TBL_PROYECTO] FOREIGN KEY([PK_FK_TBL_SIMP_PROYECTO])
REFERENCES [TBL_SIMP_PY_PROYECTO] ([PK_TBL_SIMP_PY_PROYECTO])
GO
ALTER TABLE [TBL_SIMP_USUARIOXPROYECTO] CHECK CONSTRAINT [PK_FK_TBL_PROYECTO]
GO
ALTER TABLE [TBL_SIMP_USUARIOXPROYECTO]  WITH CHECK ADD  CONSTRAINT [PK_FK_TBL_USUARIO] FOREIGN KEY([PK_FK_TBL_SIMP_USUARIO])
REFERENCES [TBL_SIMP_SEG_USUARIO] ([PK_TBL_SIMP_SEG_USUARIO])
GO
ALTER TABLE [TBL_SIMP_USUARIOXPROYECTO] CHECK CONSTRAINT [PK_FK_TBL_USUARIO]
GO
